name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - run: make
      - name: Unit tests
        run: |
          sudo apt-get update
          sudo apt-get install check
          make clean
          make units UNITS=1 && ./test/units.sh
        if: runner.os == 'Linux'
